POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hbm5fMSIsImlkIjoiNWY1MjRlZWFlZTAzYzcyM2RjNDIwY2NmIiwiaWF0IjoxNTk5MjI5NzQzfQ.MKqFoc1oywIh4O9-OR2PrSku4CjQja-HlzFlIl4P2Is

{
    "url": "www.mannawar.edu",
    "title": "Learning mongo",
    "author": "Mannawar2"
    
}